version: '3.7'

services:

    # APP SERVICES

    php:
        build: docker/php
        volumes:
            - "./symfony:/var/www/symfony:cached"
            - "./docker/php/conf/php-fpm.conf:/etc/php-fpm.conf"
            - "./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/100-php.ini"
            - "./logs/symfony:/var/www/symfony/app/var/log:cached"
        depends_on:
            - mysql
            - mysql_test

    nginx:
        build: docker/nginx
        volumes:
            - "./symfony:/var/www/symfony:cached"
            - "./docker/nginx/conf/project.conf:/etc/nginx/conf.d/00-project.conf"
            - "./logs/nginx:/var/log/nginx:cached"
        depends_on:
            - php
        ports:
            - "80:80"

    mysql:
        build: docker/mysql
        ports:
            - "3306:3306"
        environment:
          - "MYSQL_ROOT_PASSWORD=symfony"
          - "MYSQL_USER=symfony"
          - "MYSQL_PASSWORD=symfony"
          - "MYSQL_DATABASE=symfony"
        volumes:
          - "./docker/mysql/conf/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql"
          
    mysql_test:
        build: docker/mysql
        ports:
            - "3307:3306"
        environment:
          - "MYSQL_ROOT_PASSWORD=symfony_test"
          - "MYSQL_USER=symfony_test"
          - "MYSQL_PASSWORD=symfony_test"
          - "MYSQL_DATABASE=symfony_test"
        volumes:
          - "./docker/mysql/conf/db_init_test.sql:/docker-entrypoint-initdb.d/db_init_test.sql"
            
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment:
            discovery.type: "single-node"
        ports:
            - "9200:9200"

    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.4.2
        depends_on: 
            - elasticsearch
        volumes:
            - ./docker/elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
            - ./docker/elk/logstash/conf.d:/etc/logstash/conf.d:cached
            - ./logs/symfony:/var/www/symfony/app/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.4.2
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        links:
            - elasticsearch
        ports:
            - "81:5601"
