doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    types:
      book_uuid: BooksManagement\Book\Infrastructure\Persistence\Doctrine\BookUuidType
      author_uuid: BooksManagement\Author\Infrastructure\Persistence\Doctrine\AuthorUuidType

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Book:
        type: xml
        dir: "%kernel.project_dir%/../src/Book/Infrastructure/Persistence/Doctrine"
        is_bundle: false
        prefix: 'BooksManagement\Book\Domain'
        alias: BooksManagement\Book\Domain
      Author:
        type: xml
        dir: "%kernel.project_dir%/../src/Author/Infrastructure/Persistence/Doctrine"
        is_bundle: false
        prefix: 'BooksManagement\Author\Domain'
        alias: BooksManagement\Author\Domain