#!/usr/bin/env bash

docker-compose up --build -d
#docker-compose exec nginx rm -Rf var/www/symfony/app/var
sudo rm -Rf symfony/app/var
docker-compose exec php composer install
docker-compose exec php bin/console cache:clear
