<?php

namespace ContainerYIVyyNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookRepositoryMysqlService extends BooksManagement_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'BooksManagement\Book\Infrastructure\Persistence\BookRepositoryMysql' shared autowired service.
     *
     * @return \BooksManagement\Book\Infrastructure\Persistence\BookRepositoryMysql
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Book/Domain/BookRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Book/Infrastructure/Persistence/BookRepositoryMysql.php';

        return $container->privates['BooksManagement\\Book\\Infrastructure\\Persistence\\BookRepositoryMysql'] = new \BooksManagement\Book\Infrastructure\Persistence\BookRepositoryMysql(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
