<?php

namespace ContainerYIVyyNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_MessengerDebugService extends BooksManagement_App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.messenger_debug' shared service.
     *
     * @return \Symfony\Component\Messenger\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Command/DebugCommand.php';

        $container->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(['messenger.bus.default' => ['BooksManagement\\Book\\Application\\Create\\CreateBookCommand' => [0 => [0 => 'BooksManagement\\Book\\Application\\Create\\CreateBookHandler', 1 => []]], 'BooksManagement\\Book\\Application\\Find\\FindBookCommand' => [0 => [0 => 'BooksManagement\\Book\\Application\\Find\\FindBookHandler', 1 => []]]]]);

        $instance->setName('debug:messenger');

        return $instance;
    }
}
