<?php

namespace ContainerYIVyyNx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateBookControllerService extends BooksManagement_App_KernelDevDebugContainer
{
    /**
     * Gets the public 'BooksManagement\Book\EntryPoint\Http\Controller\CreateBookController' shared autowired service.
     *
     * @return \BooksManagement\Book\EntryPoint\Http\Controller\CreateBookController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Book/EntryPoint/Http/Controller/CreateBookController.php';

        return $container->services['BooksManagement\\Book\\EntryPoint\\Http\\Controller\\CreateBookController'] = new \BooksManagement\Book\EntryPoint\Http\Controller\CreateBookController(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));
    }
}
