<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMBtwCbi\BooksManagement_App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMBtwCbi/BooksManagement_App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMBtwCbi.legacy');

    return;
}

if (!\class_exists(BooksManagement_App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMBtwCbi\BooksManagement_App_KernelDevDebugContainer::class, BooksManagement_App_KernelDevDebugContainer::class, false);
}

return new \ContainerMBtwCbi\BooksManagement_App_KernelDevDebugContainer([
    'container.build_hash' => 'MBtwCbi',
    'container.build_id' => '091ff48b',
    'container.build_time' => 1597838152,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMBtwCbi');
