<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'book_get_by_id' => [['id'], ['auth' => false, '_controller' => 'BooksManagement\\Book\\EntryPoint\\Http\\Controller\\GetBookByIdController'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/book']], [], []],
    'book_store' => [[], ['auth' => false, '_controller' => 'BooksManagement\\Book\\EntryPoint\\Http\\Controller\\CreateBookController'], [], [['text', '/book']], [], []],
];
