<?php

namespace ContainerMBtwCbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_EUMUSndService extends BooksManagement_App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.eUMUSnd' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Book/Application/Create/CreateBookHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Book/Application/Create/BookCreator.php';
        include_once \dirname(__DIR__, 4).'/src/Author/Domain/AuthorRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Author/Infrastructure/Persistence/AuthorRepositoryMysql.php';

        return $container->privates['.messenger.handler_descriptor.eUMUSnd'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \BooksManagement\Book\Application\Create\CreateBookHandler(new \BooksManagement\Book\Application\Create\BookCreator(($container->privates['BooksManagement\\Book\\Infrastructure\\Persistence\\BookRepositoryMysql'] ?? $container->load('getBookRepositoryMysqlService')), new \BooksManagement\Author\Infrastructure\Persistence\AuthorRepositoryMysql(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))))), []);
    }
}
