<?php

namespace ContainerMBtwCbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_RwiWOARService extends BooksManagement_App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.rwiWOAR' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Book/Application/Find/FindBookHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Book/Application/Find/BookFinder.php';

        return $container->privates['.messenger.handler_descriptor.rwiWOAR'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \BooksManagement\Book\Application\Find\FindBookHandler(new \BooksManagement\Book\Application\Find\BookFinder(($container->privates['BooksManagement\\Book\\Infrastructure\\Persistence\\BookRepositoryMysql'] ?? $container->load('getBookRepositoryMysqlService')))), []);
    }
}
